name: Release Check

on:
  push:
    tags:
      - "v*"

jobs:
  release-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Release Check
        run: make release-check

      - name: Upload Manifest
        uses: actions/upload-artifact@v4
        with:
          name: release-manifest
          path: release/manifest/latest.json
